version: '3.8'

services:
  database:
    image: postgres:17-alpine
    container_name: task-management-db
    shm_size: 1gb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=gsc-client